// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package accounting is a generated GoMock package.
package ledger

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindAllScripts mocks base method.
func (m *MockRepository) FindAllScripts(ctx context.Context, orgID string, programID *int64) ([]Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllScripts", ctx, orgID, programID)
	ret0, _ := ret[0].([]Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllScripts indicates an expected call of FindAllScripts.
func (mr *MockRepositoryMockRecorder) FindAllScripts(ctx, orgID, programID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllScripts", reflect.TypeOf((*MockRepository)(nil).FindAllScripts), ctx, orgID, programID)
}

// FindScriptByID mocks base method.
func (m *MockRepository) FindScriptByID(ctx context.Context, orgID, scriptID string) (Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindScriptByID", ctx, orgID, scriptID)
	ret0, _ := ret[0].(Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindScriptByID indicates an expected call of FindScriptByID.
func (mr *MockRepositoryMockRecorder) FindScriptByID(ctx, orgID, scriptID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindScriptByID", reflect.TypeOf((*MockRepository)(nil).FindScriptByID), ctx, orgID, scriptID)
}

// FindScriptByLevel mocks base method.
func (m *MockRepository) FindScriptByLevel(ctx context.Context, level, eventTypeID, orgID string, programID *int64) (Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindScriptByLevel", ctx, level, eventTypeID, orgID, programID)
	ret0, _ := ret[0].(Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindScriptByLevel indicates an expected call of FindScriptByLevel.
func (mr *MockRepositoryMockRecorder) FindScriptByLevel(ctx, level, eventTypeID, orgID, programID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindScriptByLevel", reflect.TypeOf((*MockRepository)(nil).FindScriptByLevel), ctx, level, eventTypeID, orgID, programID)
}

// SaveScript mocks base method.
func (m *MockRepository) SaveScript(ctx context.Context, s Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveScript", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveScript indicates an expected call of SaveScript.
func (mr *MockRepositoryMockRecorder) SaveScript(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveScript", reflect.TypeOf((*MockRepository)(nil).SaveScript), ctx, s)
}

// UpdateScript mocks base method.
func (m *MockRepository) UpdateScript(ctx context.Context, s Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScript", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScript indicates an expected call of UpdateScript.
func (mr *MockRepositoryMockRecorder) UpdateScript(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScript", reflect.TypeOf((*MockRepository)(nil).UpdateScript), ctx, s)
}
