apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-config-app
  labels:
    com.job.service: ledger-config-app
    tier: golang
spec:
  selector: 
    matchLabels:
      com.job.service: ledger-config-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        com.job.service: ledger-config-app
        tier: golang
    spec:
      serviceAccountName: default
      containers:
        - name: accounting-app
          image: clodoaldomarques/ledger-config:latest
          imagePullPolicy: "Always"
          env:          
            - name: AWS_ADDRESS
              value: "http://localstack-service:4566"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                 secretKeyRef:
                   name: aws-secrets
                   key: AWS_ACCESS_KEY_ID 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                 secretKeyRef:
                   name: aws-secrets
                   key: AWS_SECRET_ACCESS_KEY 
            - name: AWS_REGION
              value: "us-east-1"                   
          ports:
            - name: scripts-app
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-config-app-service
  labels:
    com.job.service: ledger-config-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  selector:
    com.job.service: ledger-config-app
    tier: golang