apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-config-app
  labels:
    com.job.service: ledger-config-app
    tier: golang
spec:
  selector: 
    matchLabels:
      com.job.service: ledger-config-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        com.job.service: ledger-config-app
        tier: golang
    spec:
      serviceAccountName: default
      containers:
        - name: accounting-app
          image: clodoaldomarques/ledger-config:latest
          imagePullPolicy: "Always"
          env:
            - name: AWS_ADDRESS
              value: "http://localstack-service:4566"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                 secretKeyRef:
                   name: aws-credentials
                   key: AWS_ACCESS_KEY_ID 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                 secretKeyRef:
                   name: aws-credentials
                   key: AWS_SECRET_ACCESS_KEY 
            - name: AWS_REGION
              value: "us-east-1"
            - name: IA_URL
              value: "http://ollama-service:11434"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-service:4318"
            - name: OTEL_SERVICE_NAME
              value: "ledger-config"  
          ports:
            - name: scripts-app
              containerPort: 5000
