apiVersion: v1
kind: Service
metadata:
  name: ledger-config-app-service
  labels:
    com.job.service: ledger-config-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
  selector:
    com.job.service: ledger-config-app
    tier: golang